language: python
python:
 - "3.8"

before_install:
 - python -m pip install --upgrade pip

script:
 language: python
python:
 - "3.8"

before_install:
 - python -m pip install --upgrade pip

script:
 - python matheusferreira.py
 - python jogovelha-GabrielBarboza.py
 - python interface.py
 - python gerador-de-senhas.py
 - python funcoes.py
 - python validar-cep.py

