language: python
python:
 - "3.8"

before_install:
 - python -m pip install --upgrade pip

script:
 language: python
python:
 - "3.8"

before_install:
 - python -m pip install --upgrade pip

script:
 - python matheusferreira.py
 - python multiplicacao-GabrielBarboza.py
 - python gerador-de-senhas.py
